In [5]:
import numpy as np

In [6]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [7]:
#Numpy is Numerical python package, use  for numerical calculation 
#An array is a fundamental data structure that allows you to store and manipulate large amounts of numerical data efficiently. Think of an array as a container that holds multiple values of the same data type arranged in a grid-like structure.

In [17]:
l = [1,2,3,4,5,6,7]

In [18]:
np.array(l)

array([1, 2, 3, 4, 5, 6, 7])

In [19]:
l1 = [4,5,7,"data",34.5, True]

In [27]:
a1= np.array(l1)  # convered everything in string, dtype='<U32'--> internal representation of data type for numpy array

In [8]:
type(np.array([1,2,3,4])) #1d array

numpy.ndarray

In [26]:
a2 = np.array([[2,3,4],[3,4,7]])

In [10]:
type(np.array([[2,3,4],[3,4,7]]))  # 2d array

numpy.ndarray

In [11]:
np.array([[1,2,3,4], [2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [29]:
l1 = [4,5,7,"data",34.5, True]

In [ ]:
a1= np.array(l1)

In [ ]:
a2 = np.array([[2,3,4],[3,4,7]])

In [30]:
a3 = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

In [31]:
a1

array(['4', '5', '7', 'data', '34.5', 'True'], dtype='<U32')

In [32]:
a2

array([[2, 3, 4],
       [3, 4, 7]])

In [33]:
a3

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
#Array Dimention 

In [34]:
a1.ndim

1

In [36]:
a2.ndim

2

In [37]:
a3.ndim

3

In [ ]:
#Size--> no of elements in array

In [38]:
a1.size

4

In [39]:
a2.size

6

In [40]:
a3.size

9

In [ ]:
#Shape--> 

In [41]:
a1.shape # 6 elements

(6,)

In [42]:
a2.shape  # 2(rows) 3 (columns)

(2, 3)

In [43]:
a3.shape # 3X3 matrix and 1 dimension

(1, 3, 3)

In [12]:
l = [[1,2,3,4], [2,3,4,5]]

In [13]:
l[0][1]

2

In [14]:
a = np.array([3,4,5,6], ndmin = 5)  # dimesion of array

In [15]:
a

array([[[[[3, 4, 5, 6]]]]])

In [24]:
a3 = np.array([[[1,2,3],[3,4,5],[6,7,8]]])

In [25]:
 a3

array([[[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]]])

In [16]:
arr.ndim

2

In [18]:
np.random.randint(1,10,(4,4))  #Generating random data set-->dimention- 4X4 range between--1,10

array([[5, 5, 9, 7],
       [2, 3, 9, 5],
       [5, 2, 2, 7],
       [5, 7, 3, 5]])

In [45]:
np.random.randint(2,50,(2, 3,4))

array([[[42, 33, 39,  8],
        [17,  9, 37, 31],
        [16, 34, 34,  9]],

       [[38, 45, 28, 38],
        [39, 46, 18, 43],
        [12, 14, 35,  5]]])

In [19]:
np.random.randint(1,10,(4,4,2)) # 3 dimention  data-->(4,4,2) 4X2 dimention array 4 times in range of 1, 10

array([[[5, 6],
        [9, 3],
        [3, 6],
        [5, 9]],

       [[8, 3],
        [3, 6],
        [8, 7],
        [7, 8]],

       [[5, 6],
        [6, 4],
        [2, 9],
        [9, 8]],

       [[7, 9],
        [9, 6],
        [9, 2],
        [1, 3]]])

In [46]:
np.random.rand(2,3)   ## randn gives data have random meana and std diviation value

array([[0.88895445, 0.00157953, 0.13948765],
       [0.68489115, 0.02185448, 0.37263745]])

In [49]:
np.random.randn(4,4)

array([[-0.5527564 ,  0.07491924, -1.36525627,  0.55965691],
       [ 1.85198749,  0.21800006,  0.58026761, -1.65885562],
       [-0.44508539, -0.34521722, -1.3504578 ,  0.06979811],
       [-1.25123737,  0.68133991,  0.29596262, -0.62371162]])

In [ ]:
# randn gives normal distribution data have mean = 0 and std diviation = 1

In [51]:
 a4 = np.random.randn(4,4)

In [52]:
a4.reshape(3,4)  # will not work it should have same size or factorial of original data i.e 4X4 = 16, 8X2 = 16 , 16X1

ValueError: cannot reshape array of size 16 into shape (3,4)

In [53]:
a4.reshape(8,2)

array([[ 0.40972776,  0.46021965],
       [-0.32657427, -0.23531533],
       [ 1.52018399, -0.69038498],
       [ 0.81754594,  0.30389067],
       [ 1.54708997, -0.09191602],
       [-0.72007141, -0.3763987 ],
       [ 1.02664807, -1.39034724],
       [-0.81469463,  0.17373761]])

In [54]:
a4.reshape(2,-1)  # in this numpy will check factorial of that no on place of negative no

array([[ 0.40972776,  0.46021965, -0.32657427, -0.23531533,  1.52018399,
        -0.69038498,  0.81754594,  0.30389067],
       [ 1.54708997, -0.09191602, -0.72007141, -0.3763987 ,  1.02664807,
        -1.39034724, -0.81469463,  0.17373761]])

In [55]:
a4.reshape(2,2,4)

array([[[ 0.40972776,  0.46021965, -0.32657427, -0.23531533],
        [ 1.52018399, -0.69038498,  0.81754594,  0.30389067]],

       [[ 1.54708997, -0.09191602, -0.72007141, -0.3763987 ],
        [ 1.02664807, -1.39034724, -0.81469463,  0.17373761]]])

In [56]:
a4.reshape(1,1,1,2,2,4)

array([[[[[[ 0.40972776,  0.46021965, -0.32657427, -0.23531533],
           [ 1.52018399, -0.69038498,  0.81754594,  0.30389067]],

          [[ 1.54708997, -0.09191602, -0.72007141, -0.3763987 ],
           [ 1.02664807, -1.39034724, -0.81469463,  0.17373761]]]]]])

In [57]:
a1

array(['4', '5', '7', 'data', '34.5', 'True'], dtype='<U32')

In [58]:
a1[0]

'4'

In [59]:
a1[2:5]

array(['7', 'data', '34.5'], dtype='<U32')

In [60]:
a1[1:5:2]

array(['5', 'data'], dtype='<U32')

In [61]:
a1[::-1]

array(['True', '34.5', 'data', '7', '5', '4'], dtype='<U32')

In [62]:
a2

array([[2, 3, 4],
       [3, 4, 7]])

In [63]:
a2[0]

array([2, 3, 4])

In [66]:
a2[:,1:] 

array([[3, 4],
       [4, 7]])

In [ ]:
''''' : before the comma represents selecting all rows in the array. Since there is no specific range specified, it selects all rows. So, a2[:, ...] effectively selects all rows of the array.

, separates the row and column selections.

1: after the comma specifies the column selection. It selects all columns starting from index 1 up to the end.
By combining the row and column selections, the expression a2[:, 1:] selects all rows and the columns starting from index 1 (the second column) up to the end.'''''

In [67]:
a2[:,[1,2]]

array([[3, 4],
       [4, 7]])

In [68]:
a2[[0,1],1:]

array([[3, 4],
       [4, 7]])

In [69]:
a2[[0,1],[1,2]]  #, separates the row and column selections.

array([3, 7])

In [70]:
a2[[0,1],1:]

array([[3, 4],
       [4, 7]])

In [72]:
a5 = np.random.randint(2,90,(6,5))

In [73]:
a5

array([[40, 30, 75, 82, 54],
       [13,  3, 27, 17, 67],
       [23, 81, 72, 33, 77],
       [72, 21, 74, 46, 25],
       [ 9, 22, 63, 73, 27],
       [68, 66,  3, 84, 30]])

In [74]:
a5[a5>40]  #element greater than 40

array([75, 82, 54, 67, 81, 72, 77, 72, 74, 46, 63, 73, 68, 66, 84])

In [ ]:
#Change elements in array a5

In [75]:
a5[0,1]  #0,1 is coordinates

30

In [76]:
a5[0,1] = 31

In [77]:
a5

array([[40, 31, 75, 82, 54],
       [13,  3, 27, 17, 67],
       [23, 81, 72, 33, 77],
       [72, 21, 74, 46, 25],
       [ 9, 22, 63, 73, 27],
       [68, 66,  3, 84, 30]])

In [84]:
a6 = np.random.randint(0,3,(3,3))

In [79]:
a7 = np.random.randint(0,3,(3,3))

In [85]:
a6

array([[0, 0, 1],
       [2, 2, 1],
       [2, 1, 0]])

In [81]:
a7

array([[1, 0, 2],
       [0, 0, 2],
       [2, 2, 1]])

In [86]:
a6*a7 # element vise multiplication

array([[0, 0, 2],
       [0, 0, 2],
       [4, 2, 0]])

In [87]:
a6@a7  #Matrix Multiplication

array([[2, 2, 1],
       [4, 2, 9],
       [2, 0, 6]])

In [88]:
a6+100

array([[100, 100, 101],
       [102, 102, 101],
       [102, 101, 100]])

In [89]:
a6*2

array([[0, 0, 2],
       [4, 4, 2],
       [4, 2, 0]])

In [90]:
a6/0

C:\Users\Lenovo\AppData\Local\Temp/ipykernel_14972/1058679823.py:1: RuntimeWarning: divide by zero encountered in divide
  a6/0
C:\Users\Lenovo\AppData\Local\Temp/ipykernel_14972/1058679823.py:1: RuntimeWarning: invalid value encountered in divide
  a6/0


array([[nan, nan, inf],
       [inf, inf, inf],
       [inf, inf, nan]])

In [91]:
a6**3

array([[0, 0, 1],
       [8, 8, 1],
       [8, 1, 0]], dtype=int32)

In [93]:
a8 = np.zeros((4,4))

In [94]:
a8

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
a9 = np.ones((4,5))

In [97]:
a9

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
a9 + 10

array([[11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.],
       [11., 11., 11., 11., 11.]])

In [99]:
a9 + np.array([1,2,3,4,5])  # braodcasting operations= row vise addition, need equal elements

array([[2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6.]])

In [101]:
np.array([[1,2,3,4]]).T  # transpose operation, need 2 brakets

array([[1],
       [2],
       [3],
       [4]])

In [102]:
np.array([[1,2,3,4]]).T + a9

array([[2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5.]])

In [103]:
a6

array([[0, 0, 1],
       [2, 2, 1],
       [2, 1, 0]])

In [104]:
a6.T

array([[0, 2, 2],
       [0, 2, 1],
       [1, 1, 0]])

In [105]:
a5

array([[40, 31, 75, 82, 54],
       [13,  3, 27, 17, 67],
       [23, 81, 72, 33, 77],
       [72, 21, 74, 46, 25],
       [ 9, 22, 63, 73, 27],
       [68, 66,  3, 84, 30]])

In [106]:
np.sqrt(a5)

array([[6.32455532, 5.56776436, 8.66025404, 9.05538514, 7.34846923],
       [3.60555128, 1.73205081, 5.19615242, 4.12310563, 8.18535277],
       [4.79583152, 9.        , 8.48528137, 5.74456265, 8.77496439],
       [8.48528137, 4.58257569, 8.60232527, 6.78232998, 5.        ],
       [3.        , 4.69041576, 7.93725393, 8.54400375, 5.19615242],
       [8.24621125, 8.1240384 , 1.73205081, 9.16515139, 5.47722558]])

In [107]:
np.exp(a5)

array([[2.35385267e+17, 2.90488497e+13, 3.73324200e+32, 4.09399696e+35,
        2.83075330e+23],
       [4.42413392e+05, 2.00855369e+01, 5.32048241e+11, 2.41549528e+07,
        1.25236317e+29],
       [9.74480345e+09, 1.50609731e+35, 1.85867175e+31, 2.14643580e+14,
        2.75851345e+33],
       [1.85867175e+31, 1.31881573e+09, 1.37338298e+32, 9.49611942e+19,
        7.20048993e+10],
       [8.10308393e+03, 3.58491285e+09, 2.29378316e+27, 5.05239363e+31,
        5.32048241e+11],
       [3.40427605e+29, 4.60718663e+28, 2.00855369e+01, 3.02507732e+36,
        1.06864746e+13]])

In [108]:
np.log10(a5)

array([[1.60205999, 1.49136169, 1.87506126, 1.91381385, 1.73239376],
       [1.11394335, 0.47712125, 1.43136376, 1.23044892, 1.8260748 ],
       [1.36172784, 1.90848502, 1.8573325 , 1.51851394, 1.88649073],
       [1.8573325 , 1.32221929, 1.86923172, 1.66275783, 1.39794001],
       [0.95424251, 1.34242268, 1.79934055, 1.86332286, 1.43136376],
       [1.83250891, 1.81954394, 0.47712125, 1.92427929, 1.47712125]])

In [109]:
range(0,10)

range(0, 10)

In [110]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [111]:
list(range(0,10,2)) 

[0, 2, 4, 6, 8]

In [112]:
list(range(0,10,2.5)) # jump of 2.5 is not possible

TypeError: 'float' object cannot be interpreted as an integer

In [113]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.arange(1,10,2.5)

array([1. , 3.5, 6. , 8.5])

In [115]:
np.arange(1.7,10.5,2.5)

array([1.7, 4.2, 6.7, 9.2])

In [117]:
np.linspace(2,3, num = 50)  # to generate 50 numbers in equal no between 2 to 3

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [118]:
np.linspace(2,3, num = 50, retstep = True)  # retstep is step/jump size

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

In [119]:
np.logspace(2,4, num = 4, base = 10)

array([  100.        ,   464.15888336,  2154.43469003, 10000.        ])

In [120]:
np.logspace(2,4, num = 4, base = 11)

array([  121.        ,   598.47658063,  2960.11750055, 14641.        ])

In [ ]:
# Identity matrix , dia = 1 dim =1 r = c

In [121]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])